title: Braintree Support
description:  Support and Documentation for Lightspeed Implementation
theme: jekyll-theme-cayman
# theme: jekyll-theme-midnight
github:
  is_project_page: false
logo: /images/logo.png